services:
  - type: web
    name: watermark-remover
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5000
